### ISSUE TITLE
Does not build with ghc-9.6

### ISSUE THREAD

**Issue by erikd** [haskell-streaming/streaming#119]
When building this with `ghc-9.6` (as a dependency of another package) it fails with:

```
src/Data/Functor/Of.hs:81:3: warning: [-Wnoncanonical-monad-instances]
    Noncanonical ‘(>>)’ definition detected
    in the instance declaration for ‘Monad (Of a)’.
    ‘(>>)’ will eventually be removed in favour of ‘(*>)’
    Either remove definition for ‘(>>)’ (recommended) or define as ‘(>>) = (*>)’
    See also: https://gitlab.haskell.org/ghc/ghc/-/wikis/proposal/monad-of-no-return
   |
81 |   (m :> _) >> (m' :> y) = mappend m m' :> y
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2 of 4] Compiling Streaming.Internal ( src/Streaming/Internal.hs, dist/build/Streaming/Internal.o, dist/build/Streaming/Internal.dyn_o )

src/Streaming/Internal.hs:209:10: error: [GHC-39999]
    • Could not deduce ‘Show (f (Stream f m a))’
        arising from the head of a quantified constraint
        arising from the superclasses of an instance declaration
      from the context: (Monad m, Functor f, Show (m ShowSWrapper),
                         Show (f ShowSWrapper))
        bound by the instance declaration
        at src/Streaming/Internal.hs:(209,10)-(210,30)
      or from: Show a
        bound by a quantified context
        at src/Streaming/Internal.hs:(209,10)-(210,30)
    • In the instance declaration for ‘Show1 (Stream f m)’
    |
209 | instance (Monad m, Functor f, Show (m ShowSWrapper), Show (f ShowSWrapper))
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

**Comment by erikd** [comment]
I see HEAD is fixed. I will use a `source-repository-package` stanza in my `cabal.project` file for now.

**Comment by andreasabel** [comment]
Me too.
Made a respective revision on hackage: https://hackage.haskell.org/package/streaming-0.2.3.1/revisions/

**Comment by ocharles** [comment]
`streaming-0.2.4.0` is now on Hackage which should build on GHC 9.6
